FROM almalinux:8
RUN yum install -nginx -y
CMD ["ping", "google.com"]

# docker build -t ENTRYPOINT:v1
# docker run  ENTRYPOINT:v1
# check docker ps -a

# docker run ENTRYPOINT:v1 ping yahoo.com

# so command can overide while creating container